name: Container-Collector
run-name: ${{ github.actor }} is Collecting 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Update weekly on Monday Midnight
  workflow_dispatch:
    
jobs:
  Date:
    runs-on: ubuntu-latest
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\n$GITHUB_OUTPUT\n"
          cat $GITHUB_OUTPUT

  Collect1:
    needs: [Date]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set ROOTDIR
        run: |
          echo "ROOTDIR=Container-Collection"
          echo "ROOTDIR=$ROOTDIR" >> $GITHUB_ENV

      - name: Run Collection Script for $ROOTDIR.txt
        run: ./collect.sh $ROOTDIR.txt

      - name: Install mkisofs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mkisofs
      
      - name: Make ISO
        run: |
          echo -e "\nMaking ISO of $ROOTDIR"
          mkisofs -J -R -v -T -l \
            -V '$ROOTDIR-${{ needs.Date.outputs.Date }}' \
            -A '$ROOTDIR-${{ needs.Date.outputs.Date }}' \
            -o $ROOTDIR-${{ needs.Date.outputs.Date }}.iso \
            $ROOTDIR

      - name: Show ISO
        run: ls -alh *.iso
        
      - name: Send ISO to Sharepoint
        uses: JacobsFederal/sharepoint-file-upload-action@pappasjfed-patch-1
        with:
          file_path: "*.iso"
          host_name: 'jacobsfederal.sharepoint.us'
          site_name: 'USCMSNISSCII.DSO'
          upload_path: '${{ vars.SHAREPOINT_BASEPATH }}/${{ vars.COLLECTOR }}/'
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_APP_ID }}
          client_secret: ${{ secrets.SHAREPOINT_APP_SECRET }}
          login_endpoint: 'login.microsoftonline.us'
          graph_endpoint: 'graph.microsoft.us'

  Collect2:
    needs: [Date]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Collection Script for Atlassian-Containers.txt
        run: ./collect.sh Atlassian-Containers.txt

      - name: Install mkisofs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mkisofs
      
      - name: Make ISO
        run: |
          echo -e "\nMaking ISO of $ROOTDIR"
          mkisofs -J -R -v -T -l \
            -V '$ROOTDIR-${{ needs.Date.outputs.Date }}' \
            -A '$ROOTDIR-${{ needs.Date.outputs.Date }}' \
            -o $ROOTDIR-${{ needs.Date.outputs.Date }}.iso \
            $ROOTDIR

      - name: Show ISO
        run: ls -alh *.iso
        
      - name: Send ISO to Sharepoint
        uses: JacobsFederal/sharepoint-file-upload-action@pappasjfed-patch-1
        with:
          file_path: "*.iso"
          host_name: 'jacobsfederal.sharepoint.us'
          site_name: 'USCMSNISSCII.DSO'
          upload_path: '${{ vars.SHAREPOINT_BASEPATH }}/${{ vars.COLLECTOR }}/'
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_APP_ID }}
          client_secret: ${{ secrets.SHAREPOINT_APP_SECRET }}
          login_endpoint: 'login.microsoftonline.us'
          graph_endpoint: 'graph.microsoft.us'