name: Collect All (Branch)
run-name: Collect containers

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  collect:
    name: Collect ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: kafka-ib
            yaml: collectors/Kafka-IB.yml
          - name: postgres-ib
            yaml: collectors/PostgreSQL-IB.yml

    uses: ./.github/workflows/collector-reusable.yml
    with:
      collector_name: ${{ matrix.name }}
      collector_yaml: ${{ matrix.yaml }}
    secrets: inherit
